import myimg2 from "../image/myimg2.jpg";
import Ambika from "../image/Ambika.JPG";
export const MyCarouselData = [
  {
    id: 1,
    image: Ambika,
    brand: "shoecom",
    title: "Women Kurta and Palazzo Set Viscose Rayon",
    color: "",
    selling_price: "₹433",
    price: "₹2,995",
    disscount: "85% off",
    size: "",
    href: "/ambika",
  },
  {
    id: 2,
    image: myimg2,
    brand: "WOXEN",
    title: "Women Kurta and Pant Set Art Silk",
    color: "",
    selling_price: "₹699",
    price: "₹2,899",
    disscount: "75% off",
    size: "",
    href: "/abhishek",
  },
  {
    id: 3,
    image: Ambika,
    brand: "LIBAS",
    title: "Women Kurta and Palazzo Set Cotton Blend",
    color: "",
    selling_price: "₹1,082",
    price: "₹2,799",
    disscount: "61% off",
    size: "",
    href: "/abhishek",
  },
  {
    id: 4,
    image:
      "https://rukminim1.flixcart.com/image/612/612/l3t2fm80/ethnic-set/o/q/7/m-9kbd183-samah-original-imageuh5a8hgwusj.jpeg?q=70",
    brand: "Samah",
    title: "Women Kurta, Pant And Dupatta Set Silk Blend, Cotton Bl...",
    color: "",
    selling_price: "₹702",
    price: "₹3,997",
    disscount: "82% off",
    size: "",
    href: "/abhishek",
  },
  {
    id: 5,
    image:
      "https://rukminim1.flixcart.com/image/612/612/k4d27ww0/shirt/q/w/t/l-el024-el-senor-original-imafnadnjp5pq6tg.jpeg?q=70",
    brand: "Klosia",
    title: "Women Kurta, Pant And Dupatta Set Viscose Rayon",
    color: "",
    selling_price: "₹664",
    price: "₹2,999",
    disscount: "77% off",
    size: "",
    href: "/ambika",
  },
  {
    id: 6,
    image: myimg2,
    brand: "WOXEN",
    title: "Women Kurta and Pant Set Art Silk",
    color: "",
    selling_price: "₹699",
    price: "₹2,899",
    disscount: "75% off",
    size: "",
    href: "",
  },
  {
    id: 7,
    image: Ambika,
    brand: "WOXEN",
    title: "Women Kurta and Pant Set Art Silk",
    color: "",
    selling_price: "₹699",
    price: "₹2,899",
    disscount: "75% off",
    size: "",
  },
  {
    id: 8,
    image:
      "https://rukminim1.flixcart.com/image/612/612/k4d27ww0/shirt/q/w/t/l-el024-el-senor-original-imafnadnjp5pq6tg.jpeg?q=70",
    brand: "WOXEN",
    title: "Women Kurta and Pant Set Art Silk",
    color: "",
    selling_price: "₹699",
    price: "₹2,899",
    disscount: "75% off",
    size: "",
  },
  {
    id: 9,
    image: myimg2,
    brand: "shoecom",
    title: "Women Kurta and Palazzo Set Viscose Rayon",
    color: "",
    selling_price: "₹433",
    price: "₹2,995",
    disscount: "85% off",
    size: "",
  },
  {
    id: 10,
    image: Ambika,
    brand: "WOXEN",
    title: "Women Kurta and Pant Set Art Silk",
    color: "",
    selling_price: "₹699",
    price: "₹2,899",
    disscount: "75% off",
    size: "",
  },
  {
    id: 11,
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/ethnic-set/2/l/r/l-6909-blue-libas-original-imafygzxftqzszfx-bb.jpeg?q=70",
    brand: "LIBAS",
    title: "Women Kurta and Palazzo Set Cotton Blend",
    color: "",
    selling_price: "₹1,082",
    price: "₹2,799",
    disscount: "61% off",
    size: "",
  },
  {
    id: 12,
    image:
      "https://rukminim1.flixcart.com/image/612/612/l3t2fm80/ethnic-set/o/q/7/m-9kbd183-samah-original-imageuh5a8hgwusj.jpeg?q=70",
    brand: "Samah",
    title: "Women Kurta, Pant And Dupatta Set Silk Blend, Cotton Bl...",
    color: "",
    selling_price: "₹702",
    price: "₹3,997",
    disscount: "82% off",
    size: "",
  },
];
